#include <stddef.h>
#include <memory.h>
#include <stdlib.h>
#include <zconf.h>
#include "external/slre.h"
#include "id_plane.h"

#ifdef VALID_ID_PLANE_DEBUG
#include <printf.h>
#define DBG(a, b) printf(a, b)
#else
#define DBG(a, b)
#endif

struct id_plane {
    char country[50];
    char regex[150];
};

static const struct id_plane id_planes[] = {
        {"Afghanistan",                     "^YA-[A-Z][A-Z][A-Z]$"},
        {"Albania",                         "^ZA-[A-Z][A-Z][A-Z]$"},
        {"Algeria",                         "^7T-[A-Z][A-Z][A-Z]$"},
        {"Andorra",                         "^C3-[A-Z][A-Z][A-Z]$"},
        {"Angola",                          "^D2-[A-Z][A-Z][A-Z]$"},
        {"Anguilla",                        "^VP-A[A-Z][A-Z]$"},
        {"Antigua and Barbuda",             "^V2-[A-Z][A-Z][A-Z]$"},
        {"Argentina",                       "^LV-[A-Z][A-Z][A-Z]$"},
        {"Argentina",                       "^LQ-[A-Z][A-Z][A-Z]$"},
        {"Armenia",                         "^EK-[0-9][0-9][0-9][0-9]$"},
        {"Australia",                       "^VH-[A-Z][A-Z][A-Z]$"},
        {"Austria",                         "^OE-([A-KBLVWX][A-Z][A-Z])|([0-59][0-9][0-9][0-9])$"},
        {"Azerbaijan",                      "^4K-(AZ[1-9][A-Z][0-9])|[0-9][0-9][0-9][0-9])$"},
        {"Bahamas",                         "^C6-[A-Z][A-Z][A-Z]$"},
        {"Bahrain",                         "^A9C-[A-Z][A-Z]$"},
        {"Bangladesh",                      "^S2-[A-Z][A-Z][A-Z]$"},
        {"Barbados",                        "^8P-[A-Z][A-Z][A-Z]$"},
        {"Belarus",                         "^EW-([0-9][0-9][0-9][0-9][0-9])|(2[0-9]{2}PA)|(1[0-9]{2}PJ)|([0-9]{4}L)|(001DA)|(001PA)|(001PB)|(85815)$"},
        {"Belgium",                         "^OO-([A-PR-ZBY-Z][A-Z][A-Z])$"},
        {"Belgium",                         "^OO-([0-9][1-9])|([1-9][0-9])|([1-4][0-9][0-9])$"},
        {"Belize",                          "^V3-[A-Z][A-Z][A-Z]$"},
        {"Benin",                           "^TY-[A-Z][A-Z]$"},
        {"Bermuda",                         "^VP-B[A-Z][A-Z]$"},
        {"Bermuda",                         "^VQ-B[A-Z][A-Z]$"},
        {"Bhutan",                          "^AS-[A-Z][A-Z][A-Z]$"},
        {"Bolivia",                         "^AS-[A-Z][A-Z][A-Z]$"},
        {"Bosnia and Herzegovina",          "^T9-[A-Z][A-Z][A-Z]$"},
        {"Bosnia and Herzegovina",          "^E7-[A-Z][A-Z][A-Z]$"},
        {"Botswana",                        "^A2-[A-Z][A-Z][A-Z]$"},
        {"Brazil",                          "^PP-[A-Z][A-Z][A-Z]$"},
        {"Brazil",                          "^PR-[A-Z][A-Z][A-Z]$"},
        {"Brazil",                          "^PS-[A-Z][A-Z][A-Z]$"},
        {"Brazil",                          "^PT-[A-Z][A-Z][A-Z]$"},
        {"Brazil",                          "^PU-[A-Z][A-Z][A-Z]$"},
        {"British Virgin Islands",          "^VP-L[A-Z][A-Z]$"},
        {"Brunei",                          "^V8-[A-Z][A-Z][A-Z]$"},
        {"Brunei",                          "^V8-[A-Z][A-Z][0-9]$"},
        {"Brunei",                          "^V8-[0-9][0-9][0-9]$"},
        {"Bulgaria",                        "^LZ-[A-Z][A-Z][A-Z]$"},
        {"Burkina Faso",                    "^XT-[A-Z][A-Z][A-Z]$"},
        {"Burundi",                         "^9U-[A-Z][A-Z][A-Z]$"},
        {"Cambodia",                        "^XU-[A-Z][A-Z][A-Z]$"},
        {"Cameroon",                        "^TJ-[A-Z][A-Z][A-Z]$"},
        {"Canada",                          "^C-[FGI][A-Z][A-Z][A-Z]$"},
        {"Canada",                          "^CF-[A-Z][A-Z][A-Z]$"},
        {"Canada",                          "^VO-[A-Z][A-Z][A-Z]$"},
        {"Cape Verde",                      "^D4-[A-Z][A-Z][A-Z]$"},
        {"Cayman Islands",                  "^VP-C[A-Z][A-Z]$"},
        {"Central African Republic",        "^TL-[A-Z][A-Z][A-Z]$"},
        {"Chad",                            "^TT-[A-Z][A-Z][A-Z]$"},
        {"Chile",                           "^CC-[A-Z][A-Z][A-Z]$"},
        {"Republic of China (Taiwan)",      "^B-[0-9][0-9][0-9][0-9][0-9]$"},
        {"People's Republic of China",      "^B-(1[5-9][0-9][0-9])|([0-9][0-9][0-9][0-9])$"},
        {"People's Republic of China",      "^B-[0-9][0-9][A-Z][A-Z]$"},
        {"Hong Kong",                       "^B-H[A-Z][A-Z]$"},
        {"Hong Kong",                       "^B-K[A-Z][A-Z]$"},
        {"Hong Kong",                       "^B-L[A-Z][A-Z]$"},
        {"Macau",                           "^B-M[A-Z][A-Z]$"},
        {"Colombia",                        "^HJ-[0-9][0-9][0-9][0-9][A-Z]$"},
        {"Colombia",                        "^HK-[0-9][0-9][0-9][0-9][A-Z]$"},
        {"Comoros",                         "^D6-[A-Z][A-Z][A-Z]$"},
        {"Congo, Republic of",              "^TN-[A-Z][A-Z][A-Z]$"},
        {"Cook Islands",                    "^E5-[A-Z][A-Z][A-Z]$"},
        {"Congo, Democratic Republic of",   "^9Q-[A-Z][A-Z][A-Z]$"},
        {"Costa Rica",                      "^TI-[A-Z][A-Z][A-Z]$"},
        {"Costa Rica",                      "^TI-[0-9][0-9][0-9]$"},
        {"Côte d'Ivoire",                   "^TU-[A-Z][A-Z][A-Z]$"},
        {"Croatia",                         "^9A-[A-Z][A-Z][A-Z]$"},
        {"Cuba",                            "^CU-[ACHNTU]1[0-9][0-9][0-9]$"},
        {"Cyprus, Republic of",             "^5B-[A-Z][A-Z][A-Z]$"},
        {"Czech Republic",                  "^OK-[A-Z][A-Z][A-Z]$"},
        {"Czech Republic",                  "^OK-[A-Z][A-Z][A-Z] [0-9][0-9]$"},
        {"Czech Republic",                  "^OK-[0-9][0-9][0-9][0-9]$"},
        {"Czech Republic",                  "^OK-A[0-9][0-9][0-9]$"},
        {"Denmark",                         "^OY-[A-Z][A-Z][A-Z]$"},
        {"Denmark",                         "^OY-1[0-9][0-9]?[0-9]?$"},
        {"Denmark",                         "^OY-8[0-9][0-9]?[0-9]?$"},
        {"Denmark",                         "^OY-9[0-9][0-9]?[0-9]?$"},
        {"Djibouti",                        "^J2-[A-Z][A-Z][A-Z]$"},
        {"Dominica",                        "^J7-[A-Z][A-Z][A-Z]$"},
        {"Dominican Republic",              "^HI-[1-9][0-9][0-9][A-Z][A-Z]$"},
        {"East Timor",                      "^4W-[A-Z][A-Z][A-Z]$"},
        {"Ecuador",                         "^HC-[A-Z][A-Z][A-Z]$"},
        {"Egypt",                           "^SU-[A-Z][A-Z][A-Z]$"},
        {"Egypt",                           "^SU-[0-9][0-9][0-9]$"},
        {"El Savador",                      "^YS-[A-Z][A-Z][A-Z]$"},
        {"Equatorial Guinea",               "^3C-[A-Z][A-Z][A-Z]$"},
        {"Equatorial Guinea",               "^3C-[A-Z][A-Z][A-Z][A-Z]$"},
        {"Estonia",                         "^ES-[A-Z][A-Z][A-Z][A-Z]$"},
        {"Ethiopia",                        "^ET-[A-Z][A-Z][A-Z]$"},
        {"Falkland Islands",                "^VP-F[A-Z][A-Z]$"},
        {"Fiji Islands",                    "^DQ[A-Z][A-Z][A-Z]$"},
        {"Finland",                         "^OH-[A-Z][A-Z][A-Z]$"},
        {"Finland",                         "^OH-[GU]?[0-9][0-9][0-9]$"},
        {"French West Indies",              "^F-OG[A-Z][A-Z]$"},
        {"French Guyana",                   "^F-O[A-Z][A-Z][A-Z]$"},
        {"France",                          "^F-[A-Z][A-Z][A-Z][A-Z]$"},
        {"France",                          "^F-[0-9][0-9]-[A-Z][A-Z][A-Z]?$"},
        {"Gabon",                           "^TR-[A-Z][A-Z][A-Z]$"},
        {"Gambia",                          "^C5-[A-Z][A-Z][A-Z]$"},
        {"Georgia",                         "^4L-[A-Z][A-Z][A-Z]$"},
        {"Georgia",                         "^4L-[0-9][0-9][0-9][0-9][0-9]$"},
        {"Germany",                         "^D-A[U-Z][A-Z][A-Z]$"},
        {"Germany",                         "^D-[BCEFGIHKLMNO][A-Z][A-Z][A-Z]$"},
        {"Germany",                         "^D-[0-9][0-9][0-9][0-9]$"},
        {"Ghana",                           "^9G-[A-Z][A-Z][A-Z]$"},
        {"Gibraltar",                       "^VP-G[A-Z][A-Z]$"},
        {"Greece",                          "^SX-[A-Z][A-Z][A-Z]$"},
        {"Greece",                          "^SX-[O-9][O-9][O-9]$"},
        {"Grenada",                         "^SX-[O-9][O-9][O-9]$"},
        {"Guatemala",                       "^TG-[O-9][O-9][O-9]$"},
        {"Guernsey",                        "^2-[A-Z][A-Z][A-Z][A-Z]$"},
        {"Guinea",                          "^3X-[A-Z][A-Z][A-Z]$"},
        {"Guinea Bissau",                   "^J5-[A-Z][A-Z][A-Z]$"},
        {"Guyana",                          "^8R-[A-Z][A-Z][A-Z]$"},
        {"Haiti",                           "^HH-[A-Z][A-Z][A-Z]$"},
        {"Honduras",                        "^HR-[A-Z][A-Z][A-Z]$"},
        {"Hungary",                         "^HA-[A-Z][A-Z][A-Z]$"},
        {"Iceland",                         "^TF-[A-Z][A-Z][A-Z]$"},
        {"Iceland",                         "^TF-[0-9][0-9][0-9]$"},
        {"India",                           "^VT-[A-Z][A-Z][A-Z]$"},
        {"Indonesia",                       "^PK-[A-Z][A-Z][A-Z]$"},
        {"Iran",                            "^EP-[A-Z][A-Z][A-Z]$"},
        {"Iraq",                            "^YI-[A-Z][A-Z][A-Z]$"},
        {"Ireland",                         "^EI-[A-Z][A-Z][A-Z][A-Z]?$"},
        {"Israel",                          "^4X-[A-Z][A-Z][A-Z]$"},
        {"Italy",                           "^I-[A-Z][A-Z][A-Z]$"},
        {"Italy",                           "^I-[0-9][0-9][0-9]$"},
        {"Jamaica",                         "^6Y-[A-Z][A-Z][A-Z]$"},
        {"Japan",                           "^JA[0-9][0-9]([0-9][0-9])|([0-9][A-Z])|([A-Z][A-Z])$"},
        {"Japan",                           "^JAA[0-9][0-9][0-9]$"},
        {"Jersey",                          "^ZJ-[A-Z][A-Z][A-Z]$"},
        {"Jordan",                          "^JY-[A-Z][A-Z][A-Z]$"},
        {"Kosovo, Republic of",             "^Z6-[A-Z][A-Z][A-Z]$"},
        {"Kazakhstan",                      "^UP-[A-Z][A-Z][A-Z][0-9][0-9]$"},
        {"Kenya",                           "^5Y-[A-Z][A-Z][A-Z]$"},
        {"Kiribati",                        "^T3-[A-Z][A-Z][A-Z]$"},
        {"Korea, People's Democratic Rep.", "^P-[5-9][0-9][0-9]$"},
        {"Korea, Republic of",              "^HL[0-9C][0-9][0-9][0-9]$"},
        {"Kuwait",                          "^9K-[A-Z][A-Z][A-Z]$"},
        {"Kyrgyzstan",                      "^EX-[0-9][0-9][0-9]([0-9][0-9])?$"},
        {"Laos",                            "^RDPL-[0-9][0-9][0-9][0-9][0-9]$"},
        {"Latvia",                          "^YL-[A-Z][A-Z][A-Z]$"},
        {"Lebanon",                         "^OD-[A-Z][A-Z][A-Z]$"},
        {"Lesotho",                         "^7P-[A-Z][A-Z][A-Z]$"},
        {"Liberia",                         "^A8-[A-Z][A-Z][A-Z]$"},
        {"Libya",                           "^5A-[A-Z][A-Z][A-Z]$"},
        {"Liechtenstein",                   "^HB-[A-Z][A-Z][A-Z]$"},
        {"Lithuania",                       "^LY-[A-Z][A-Z][A-Z]$"},
        {"Luxembourg",                      "^LX-[ABCHX][A-Z][A-Z]$"},
        {"Luxembourg",                      "^LX-N904[45][0-9]$"},
        {"Macedonia, Republic of",          "^Z3-[A-Z][A-Z][A-Z]$"},
        {"Macedonia, Republic of",          "^Z3-UA-[0-9][0-9][0-9]$"},
        {"Madagascar",                      "^5R-[A-Z][A-Z][A-Z]$"},
        {"Malawi",                          "^7Q-[A-Z][A-Z][A-Z]$"},
        {"Malaysia",                        "^9M-[A-Z][A-Z][A-Z]$"},
        {"Maldives",                        "^8Q-[A-Z][A-Z][A-Z]$"},
        {"Mali",                            "^TZ-[A-Z][A-Z][A-Z]$"},
        {"Malta",                           "^9H-[A-Z][A-Z][A-Z]$"},
        {"Isle of Man",                     "^M-[A-Z][A-Z][A-Z][A-Z]$"},
        {"Marshall Islands",                "^V7-[0-9][0-9][0-9][0-9]$"},
        {"Mauritania",                      "^5T-[A-Z][A-Z][A-Z]$"},
        {"Mauritius",                       "^3B-[A-Z][A-Z][A-Z]$"},
        {"Mexico",                          "^X[ABC]-[A-Z][A-Z][A-Z]$"},
        {"Micronesia, Federated States of", "^V6-[A-Z][A-Z][A-Z]$"},
        {"Moldova",                         "^ER-[A-Z][A-Z][A-Z]$"},
        {"Moldova",                         "^ER-[0-9][0-9][0-9][0-9][0-9]$"},
        {"Monaco",                          "^3A-[A-Z][A-Z][A-Z]$"},
        {"Mongolia",                        "^JU-[0-9][0-9][0-9][0-9]$"},
        {"Montenegro",                      "^4O-[A-Z][A-Z][A-Z]$"},
        {"Montserrat",                      "^VP-M[A-Z][A-Z]$"},
        {"Morocco",                         "^CN-[A-Z][A-Z][A-Z]$"},
        {"Mozambique",                      "^C9-[A-Z][A-Z][A-Z]$"},
        {"Myanmar",                         "^X[YZ]-[A-Z][A-Z][A-Z]$"},
        {"Namibia",                         "^V5-[A-Z][A-Z][A-Z]$"},
        {"Nauru",                           "^C2-[A-Z][A-Z][A-Z]$"},
        {"Nepal",                           "^9N-[A-Z][A-Z][A-Z]$"},
        {"Netherlands",                     "^PH-[A-Z][A-Z][A-Z]$"},
        {"Netherlands",                     "^PH-1[A-Z][A-Z0-9]$"},
        {"Netherlands",                     "^PH-[0-9][0-9][0-9][0-9]?$"},
        {"Netherlands Antilles",            "^PJ-[A-Z][A-Z][A-Z]$"},
        {"New Zealand",                     "^ZK-[ABGHIQ][A-Z0-9][A-Z0-9]$"},
        {"New Zealand",                     "^ZK-(F[AB])|(R[ABCD])[A-Z0-9]$"},
        {"Nicaragua",                       "^YN-[A-Z][A-Z][A-Z]$"},
        {"Niger",                           "^5U-[A-Z][A-Z][A-Z]$"},
        {"Nigeria",                         "^5N-[A-Z][A-Z][A-Z]$"},
        {"Norway",                          "^LN-[A-Z][A-Z][A-Z]$"},
        {"Norway",                          "^LN-[GOCY][A-Z0-9][A-Z0-9]$"},
        {"Oman",                            "^A4O-[A-Z][A-Z]$"},
        {"Pakistan",                        "^AP-[A-Z][A-Z][A-Z]$"},
        {"Palestine",                       "^E4-[A-Z][A-Z][A-Z]$"},
        {"Panama",                          "^HP-[0-9][0-9][0-9][0-9][A-Z][A-Z]$"},
        {"Papua New Guinea",                "^P2-[A-Z][A-Z][A-Z]$"},
        {"Paraguay",                        "^ZP-[A-Z][A-Z][A-Z]$"},
        {"Peru",                            "^OB-[0-9][0-9][0-9][0-9]$"},
        {"Philippines",                     "^RP-[CGRUXS]?[0-9][0-9][0-9][0-9]$"},
        {"Poland",                          "^SP-[A-Z][A-Z][A-Z]$"},
        {"Poland",                          "^SP-[0138SX][A-Z0-9][A-Z0-9][A-Z0-9]$"},
        {"Poland",                          "^SP-[BLY][A-Z0-9][A-Z0-9]$"},
        {"Poland",                          "^SN-(VP)|(VS)[A-Z0-9]$"},
        {"Poland",                          "^SN-[A-Z0-9][A-Z0-9](YG)|(XP)$"},
        {"Portugal",                        "^CR-[A-Z][A-Z][A-Z]$"},
        {"Portugal",                        "^CS-[A-Z][A-Z][A-Z]$"},
        {"Portugal",                        "^CS-[THXUPB][A-Z0-9][A-Z0-9]$"},
        {"Portugal",                        "^CS-[THXUPB][A-Z0-9][A-Z0-9]$"},
        {"Qatar",                           "^A7-[A-Z][A-Z][A-Z]$"},
        {"Réunion Island",                  "^F-OD[A-Z][A-Z]$"},
        {"Romania",                         "^YR-[A-Z][A-Z][A-Z]$"},
        {"Romania",                         "^YR-D?[0-9][0-9][0-9][0-9]$"},
        {"Russian Federation",              "^RA-[0-9][0-9][0-9][0-9][0-9KGA]$"},
        {"Russian Federation",              "^RF-[0-9][0-9][0-9][0-9][0-9]$"},
        {"Rwanda",              "^9XR-[A-Z][A-Z]$"},
        {"Saint Helena/Ascension",              "^VQ-H[A-Z][A-Z]$"},
        {"Saint Kitts and Nevis",              "^V4-[A-Z][A-Z][A-Z]$"},
        {"Saint Lucia",              "^J6-[A-Z][A-Z][A-Z]$"},
        {"Saint Vincent and the Grenadines",              "^J8-[A-Z][A-Z][A-Z]$"},
        {"Samoa",              "^5W-[A-Z][A-Z][A-Z]$"},
        {"San Marino",              "^T7-[A-Z][A-Z][A-Z]$"},
        {"San Marino",              "^T7-[0-9][0-9][0-9]$"},
        {"São Tomé and Príncipe",              "^S9-[A-Z][A-Z][A-Z]$"},
        {"Saudi Arabia",              "^HZ-[A-Z][A-Z][A-Z][A-Z]?$"},
        {"Saudi Arabia",              "^HZ-[A-Z][A-Z][0-9][0-9]?$"},
        {"Saudi Arabia",              "^HZ-[A-Z][A-Z][A-Z][0-9][0-9]?$"},
        {"Senegal",              "^6V-[A-Z][A-Z][A-Z]$"},
        {"Serbia",              "^6V-[A-Z][A-Z][A-Z]$"},
        {"Serbia",              "^6V-[A-Z]?[0-9][0-9][0-9]$"},
        {"Seychelles",              "^S7-[A-Z][A-Z][A-Z]$"},
        {"Sierra Leone",              "^9L-[A-Z][A-Z][A-Z]$"},
        {"Singapore",              "^9V-[A-Z][A-Z][A-Z]$"},
        {"Slovakia",              "^OM-[A-Z][A-Z][A-Z][A-Z]$"},
        {"Slovakia",              "^OM-[M0-9][0-9][0-9][0-9]$"},
        {"Slovenia",              "^S5-[A-Z0-9][A-Z0-9][A-Z0-9][A-Z0-9]?$"},
        {"Solomon Islands",              "^H4-[A-Z][A-Z][A-Z]$"},
        {"Somalia",              "^6O-[A-Z][A-Z][A-Z]$"},
        {"South Africa",              "^Z[STU]-[A-Z][A-Z][A-Z]$"},
        {"South Sudan",              "^Z8-[A-Z][A-Z][A-Z]$"},
        {"Spain",              "^EC-[A-Z][A-Z][A-Z]$"},
        {"Spain",              "^EC-[0-9][0-9][0-9]$"},
        {"Sri Lanka",              "^4R-[A-Z][A-Z][A-Z]$"},
        {"Sudan",              "^ST-[A-Z][A-Z][A-Z]$"},
        {"Surinam",              "^PZ-[A-Z][A-Z][A-Z]$"},
        {"Swaziland",              "^3D-[A-Z][A-Z][A-Z]$"},
        {"Sweden",              "^SE-[A-Z][A-Z][A-Z]$"},
        {"Sweden",              "^SE-[A-Z][0-9][0-9]$"},
        {"Switzerland",              "^HB-[A-Z][A-Z][A-Z]$"},
        {"Syria",              "^YK-[A-Z][A-Z][A-Z]$"},
        {"Tahiti",              "^F-OH[A-Z][A-Z]$"},
        {"Tajikistan",              "^EY-[0-9][0-9][0-9][0-9][0-9]$"},
        {"Tanzania",              "^5H-[A-Z][A-Z][A-Z]$"},
        {"Thailand",              "^HS-[A-Z][A-Z][A-Z]$"},
        {"Togo",              "^5V-[A-Z][A-Z][A-Z]$"},
        {"Tonga",              "^A3-[A-Z][A-Z][A-Z]$"},
        {"Trinidad and Tobago",              "^9Y-[A-Z][A-Z][A-Z]$"},
        {"Tunisia",              "^TS-[A-Z][A-Z][A-Z]$"},
        {"Turkey",              "^TC-[A-Z][A-Z][A-Z]$"},
        {"Turkmenistan",              "^EZ-[A-Z][A-Z][A-Z]$"},
        {"Turks and Caicos",              "^VQ-T[A-Z][A-Z]$"},
        {"Tuvalu",              "^T2-[A-Z][A-Z][A-Z]$"},
        {"Uganda",              "^5X-[A-Z][A-Z][A-Z]$"},
        {"Ukraine",              "^UR-[A-Z][A-Z][A-Z][A-Z]?$"},
        {"Ukraine",              "^UR-[0-9][0-9][0-9][0-9][0-9]$"},
        {"United Arab Emirates",              "^A6-[A-Z][A-Z][A-Z]$"},
        {"United Kingdom",              "^G-[A-Z][A-Z][A-Z][A-Z]$"},
        {"United Kingdom",              "^G-[0-9][0-9]?-[0-9][0-9]?$"},
        {"United Nations[d]",              "^4U-[A-Z][A-Z][A-Z]$"},
        {"United States of America",              "^N[0-9][0-9]?[0-9]?[0-9]?[0-9]?$"},
        {"United States of America",              "^N[0-9][0-9]?[0-9]?[0-9]?[A-Z]$"},
        {"United States of America",              "^N[0-9][0-9]?[0-9]?[A-Z][A-Z]$"},
        {"Uruguay",              "^CX-[A-Z][A-Z][A-Z]$"},
        {"Uzbekistan",              "^UK[0-9][0-9][0-9][0-9][0-9]$"},
        {"Vanuatu",              "^YJ-[A-Z][A-Z][0-9][0-9]?$"},
        {"Venezuela",              "^YV[0-9][0-9][0-9][0-9TE]$"},
        {"Venezuela",              "^YVO[0-9][0-9][0-9]$"},
        {"Vietnam",              "^VN-[0-9ABC][0-9][0-9][0-9]$"},
        {"Yemen",              "^7O-[A-Z][A-Z][A-Z]$"},
        {"Zambia",              "^9J-[A-Z][A-Z][A-Z]$"},
        {"Zimbabwe",              "^Z-[A-Z][A-Z][A-Z]$"}
};

int faillist_valid_header_id_plane(faillist_validated_data_header_t *header, unsigned char id_plane[]) {
    if (header == NULL) {
        return EXIT_FAILURE;
    }

    size_t l = strlen((const char *) id_plane); // get the length of id_plane parameter for slre_match (used as cache)

    for (unsigned int i = 0; i < 277; i++) { // loop over every id_planes element
        DBG("%s:", id_planes[i].country);

        if (slre_match(id_planes[i].regex, (const char *) id_plane, (int) l, NULL, 0, 0) > 0) {
            DBG("OK\n", NULL);

            // the id_plane is valid and matched copy the id_plane and matching nationality to the header structure
            strcpy(header->id_plane, (const char *) id_plane);
            strcpy(header->nationality, id_planes[i].country);

            return EXIT_SUCCESS;
        } else {
            DBG("KO\n", NULL);
        }
    }
    return EXIT_FAILURE;
}
